############################
## CHANGE THESE
############################

baseURL: "https://Nanqi-code.github.io/qubtTemplateFor277"
title: qubtTemplateFor277

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
